# Generated by Django 5.0.8 on 2024-08-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='variants',
            field=models.CharField(default='a)3,b)5,c)2,d)6', max_length=255),
        ),
    ]
